/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export type Project = {
    _id: string;
    _type: 'project';
    image?: {
        _type: 'image';
        asset: {
            _ref: string;
            _type: 'reference';
        };
    };
    title: string;
    description: string;
    slug: {
        _type: 'slug';
        current: string;
    };
    techStack: string[]; // or PortableTextBlock[] if you use rich text
    link?: string;
    createdAt: string; // ISO date string
};

export type Hero = {
    _id: string;
    _type: 'hero';
    role: string;
    name: string;
    description: string;
    resume?: string;
};

export type Experience = {
    _id: string;
    _type: 'experience';
    date: string;
    title: string;
    description: string;
};

export type Social = {
    _id: string;
    _type: 'social';
    icon: string;
    label: string;
    link: string;
};
